export const sellers = ["adam", "bobby", "calvin", "danny", "elvin", "freddy"];

export const languages = ["English", "Chinese", "Malay", "Tamil", "Spanish", "Japanese", "Korean"];

export const categories = [
  "Non-Fiction",
  "Fiction",
  "Classic Literature",
  "Business",
  "Romance",
  "History",
  "Mystery",
  "Biography & Autobiography",
  "Thriller",
  "Fantasy",
  "Self-Improvement",
  "Young Adult Fiction",
  "Sociology",
  "Politics",
  "Science",
  "Health & Fitness",
  "Cooking & Food",
  "Science Fiction",
  "Comic and Graphic Books",
  "Psychology",
  "Nature",
  "Travel",
  "Education",
  "Economics",
  "Art",
  "Technology",
  "Philosophy",
  "Medical",
  "Horror",
  "Music",
  "Poetry",
  "Law",
  "Architecture",
  "Pets",
  "Games",
  "Photography",
  "Drama",
  "Geography",
  "Gardening",
  "Engineering",
];

export const books = [
  { title: "Harry Potter and the Philosopher's Stone", author: "J. K. Rowling", tags: ["magic", "hogwarts"] },
  { title: "Harry Potter and the Chamber of Secrets", author: "J. K. Rowling", tags: ["magic", "hogwarts"] },
  { title: "Harry Potter and the Prisoner of Azkaban", author: "J. K. Rowling", tags: ["magic", "hogwarts"] },
  { title: "Harry Potter and the Goblet of Fire", author: "J. K. Rowling", tags: ["magic", "hogwarts"] },
  { title: "Harry Potter and the Order of the Phoenix", author: "J. K. Rowling", tags: ["magic", "hogwarts"] },
  { title: "Harry Potter and the Half-Blood Prince", author: "J. K. Rowling", tags: ["magic", "hogwarts"] },
  { title: "Harry Potter and the Deathly Hallows", author: "J. K. Rowling", tags: ["magic", "hogwarts"] },
  { title: "James and the Giant Peach", author: "Roald Dahl", tags: [] },
  { title: "Charlie and the Chocolate Factory", author: "Roald Dahl", tags: ["willy wonka"] },
  { title: "Fantastic Mr Fox", author: "Roald Dahl", tags: [] },
  { title: "Charlie and the Great Glass Elevator", author: "Roald Dahl", tags: ["willy wonka"] },
  { title: "The Twits", author: "Roald Dahl", tags: [] },
  { title: "The BFG", author: "Roald Dahl", tags: ["big friendly giant"] },
  { title: "Matilda", author: "Roald Dahl", tags: [] },
  { title: "The Gremlins", author: "Roald Dahl", tags: [] },
  { title: "Sometime Never: A Fable for Supermen", author: "Roald Dahl", tags: [] },
  { title: "The Magic Finger", author: "Roald Dahl", tags: [] },
  { title: "Danny, the Champion of the World", author: "Roald Dahl", tags: [] },
  { title: "The Enormous Crocodile", author: "Roald Dahl", tags: [] },
  { title: "My Uncle Oswald", author: "Roald Dahl", tags: [] },
  { title: "George's Marvellous Medicine", author: "Roald Dahl", tags: [] },
  { title: "The Witches", author: "Roald Dahl", tags: [] },
  { title: "The Giraffe and the Pelly and Me", author: "Roald Dahl", tags: [] },
  { title: "Esio Trot", author: "Roald Dahl", tags: [] },
  { title: "The Vicar of Nibbleswicke", author: "Roald Dahl", tags: [] },
  { title: "The Minpins", author: "Roald Dahl", tags: [] },
];
